services:
  db:
    image: postgres:15-alpine
    container_name: roomnexus-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: roomnexus-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PG_PORT}:${PG_CONTAINER_PORT}"
    depends_on:
      - db

  app:
    build: .
    container_name: roomnexus-app
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${APP_PORT}
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_PORT=${APP_PORT}

volumes:
  postgres_data: